package com.randonautica.app.Attractors;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.graphics.Color;
import android.util.Base64;
import android.view.View;

import com.mapbox.mapboxsdk.annotations.MarkerOptions;
import com.mapbox.mapboxsdk.annotations.PolygonOptions;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.randonautica.app.Classes.AttractorLocation;
import com.randonautica.app.Classes.DatabaseHelper;
import com.randonautica.app.Classes.SingleRecyclerViewLocation;
import com.randonautica.app.Interfaces.API_Classes.Attractors;
import com.randonautica.app.Interfaces.API_Classes.PseudoAttractor;
import com.randonautica.app.Interfaces.API_Classes.Sizes;
import com.randonautica.app.Interfaces.RandoWrapperApi;
import com.randonautica.app.Interfaces.RandonautAttractorListener;
import com.randonautica.app.MyRandonautFragment;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.TimeUnit;

import okhttp3.OkHttpClient;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public class GenerateAttractors extends Activity {

    //Pseudo range
    private int N;

    //Contains locations generated by attractor functions
    public static ArrayList<SingleRecyclerViewLocation> locationList = new ArrayList<>();

    //initialize Classes
    DatabaseHelper mDatabaseHelper;
    RandoWrapperApi randoWrapperApi;
    ProgressDialog progressdialog;

    //Database tables to store attractors
    String attractorTable = "Attractors";
    String voidTable = "Voids";
    String anomalyTable = "Anomalies";

    public void getAttractors(final View view, final MapboxMap mapboxMap, final Context context,
                              String GID, boolean pool, boolean temporal, boolean gcp, final String selected, int distance, final RandonautAttractorListener randonautDialogsListener){
        //Empty previous run
        locationList = new ArrayList<>();
        mapboxMap.clear();

        //Start ProgressDialog
        progressdialog = new ProgressDialog(context);
        progressdialog.setMessage("Looking for " + selected + "s " + "please wait....");
        progressdialog.show();
        progressdialog.setCancelable(false);
        progressdialog.setCanceledOnTouchOutside(false);

        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .connectTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .build();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(new String(Base64.decode(MyRandonautFragment.getBaseApi(),Base64.DEFAULT)))
                .client(okHttpClient)
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        randoWrapperApi = retrofit.create(RandoWrapperApi.class);

        Call<List<Attractors>> callGetAttractors = randoWrapperApi.getAttractors(GID,
                mapboxMap.getLocationComponent().getLastKnownLocation().getLatitude(), mapboxMap.getLocationComponent().getLastKnownLocation().getLongitude(), distance, pool, temporal, gcp);

        callGetAttractors.enqueue(new Callback<List<Attractors>>() {
            @Override
            public void onResponse(Call<List<Attractors>> call, Response<List<Attractors>> response) {

                int i = 0;
                int count = 0;
                int amount = 0;

                for(Attractors attractors: response.body()){
                    count ++;
                }

                AttractorLocation attractorLocations[] =new AttractorLocation[count];

                for(Attractors attractors: response.body()){

                    //First Part
                    String GID = attractors.getAttractors().getGID();
                    String TID = attractors.getAttractors().getTID();
                    String LID = attractors.getAttractors().getLID();
                    int type = attractors.getAttractors().getType();
                    double x_ = attractors.getAttractors().getX();
                    double y_ = attractors.getAttractors().getY();


                    //Second part
                    double x = attractors.getAttractors().getCenter().getLatlng().getPoint().getLatitude(); //Used in map
                    double y = attractors.getAttractors().getCenter().getLatlng().getPoint().getLongitude(); //Used in map

                    double distance = attractors.getAttractors().getCenter().getLatlng().getBearing().getDistance();
                    double initialBearing = attractors.getAttractors().getCenter().getLatlng().getBearing().getInitialBearing();
                    double finalBearing = attractors.getAttractors().getCenter().getLatlng().getBearing().getFinalBearing();

                    //Third part
                    int side = attractors.getAttractors().getSide();
                    double distanceErr = attractors.getAttractors().getDistanceErr();
                    double radiusM = attractors.getAttractors().getRadiusM();
                    int n = attractors.getAttractors().getN();
                    double mean = attractors.getAttractors().getMean();
                    int rarity = attractors.getAttractors().getRarity();
                    double power_old = attractors.getAttractors().getPower_old();
                    double power = attractors.getAttractors().getPower();
                    double z_score = attractors.getAttractors().getZ_score();
                    double probability_single = attractors.getAttractors().getProbability_single();
                    double integral_score = attractors.getAttractors().getIntegral_score();
                    double significance = attractors.getAttractors().getSignificance();
                    double probability = attractors.getAttractors().getProbability();
                    int FILTERING_SIGNIFICANCE = attractors.getAttractors().getFILTERING_SIGNIFICANCE();

                    attractorLocations[i]=new AttractorLocation(new LatLng(x, y), GID,  TID,  LID,  x_,  y_,  distance,  initialBearing,  finalBearing, side,  distanceErr,  radiusM, n,  mean, rarity,  power_old,  probability_single,  integral_score,  significance,  probability, FILTERING_SIGNIFICANCE, type, radiusM,  power,  z_score);

                    if(selected == "Attractor" && type == 1){
                        //Make databaseHelper
                        mDatabaseHelper = new DatabaseHelper(context, attractorTable);

                        //Generate Marker
                        mapboxMap.addMarker(new MarkerOptions()
                                .position(new LatLng(x, y))
                                .title("Attractor"));

                        //Generate Circle
                        mapboxMap.addPolygon(generatePerimeter(
                                new LatLng(x, y),
                                (radiusM/1000),
                                64));

                        amount++;
                        MyRandonautFragment.atts++;
                        SingleRecyclerViewLocation singleLocation = new SingleRecyclerViewLocation();
                        singleLocation.setType((attractorLocations[i].getType()));
                        singleLocation.setRadiusm((attractorLocations[i].getRadiusM()));
                        singleLocation.setPower((attractorLocations[i].getPower()));
                        singleLocation.setZ_score((attractorLocations[i].getZ_score()));
                        singleLocation.setLocationCoordinates(attractorLocations[i].getCoordinate());
                        singleLocation.setPsuedo(false);
                        //getRoutesToAllPoints(attractorLocations[i].getCoordinate());

                        AddData(attractorTable,
                                attractorLocations[i].getCoordinate().getLatitude(),
                                attractorLocations[i].getCoordinate().getLongitude(),
                                attractorLocations[i].getGID(),
                                attractorLocations[i].getTID(),
                                attractorLocations[i].getLID(),

                                attractorLocations[i].getX(),
                                attractorLocations[i].getY(),
                                attractorLocations[i].getDistance(),
                                attractorLocations[i].getInitialBearing(),
                                attractorLocations[i].getFinalBearing(),
                                attractorLocations[i].getSide(),
                                attractorLocations[i].getDistanceErr(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getN(),
                                attractorLocations[i].getMean(),
                                attractorLocations[i].getRarity(),
                                attractorLocations[i].getPower_old(),
                                attractorLocations[i].getProbability_single(),
                                attractorLocations[i].getIntegral_score(),
                                attractorLocations[i].getSignificance(),
                                attractorLocations[i].getProbability(),
                                attractorLocations[i].getFILTERING_SIGNIFICANCE(),
                                attractorLocations[i].getType(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getPower(),
                                attractorLocations[i].getZ_score(),
                                0, 0);

                        locationList.add(singleLocation);

                    }

                    if(selected == "Void" && type == 2){
                        mDatabaseHelper = new DatabaseHelper(context, voidTable);

                        //Generate Marker
                        mapboxMap.addMarker(new MarkerOptions()
                                .position(new LatLng(x, y))
                                .title("Void"));

                        //Generate Circle
                        mapboxMap.addPolygon(generatePerimeter(
                                new LatLng(x, y),
                                (attractorLocations[i].getRadiusM()/1000),
                                64));

                        amount++;
                        MyRandonautFragment.voids++;
                        SingleRecyclerViewLocation singleLocation = new SingleRecyclerViewLocation();
                        singleLocation.setType((attractorLocations[i].getType()));
                        singleLocation.setRadiusm((attractorLocations[i].getRadiusM()));
                        singleLocation.setPower((attractorLocations[i].getPower()));
                        singleLocation.setZ_score((attractorLocations[i].getZ_score()));
                        singleLocation.setLocationCoordinates(attractorLocations[i].getCoordinate());
                        singleLocation.setPsuedo(false);

                        AddData(voidTable,
                                attractorLocations[i].getCoordinate().getLatitude(),
                                attractorLocations[i].getCoordinate().getLongitude(),
                                attractorLocations[i].getGID(),
                                attractorLocations[i].getTID(),
                                attractorLocations[i].getLID(),

                                attractorLocations[i].getX(),
                                attractorLocations[i].getY(),
                                attractorLocations[i].getDistance(),
                                attractorLocations[i].getInitialBearing(),
                                attractorLocations[i].getFinalBearing(),
                                attractorLocations[i].getSide(),
                                attractorLocations[i].getDistanceErr(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getN(),
                                attractorLocations[i].getMean(),
                                attractorLocations[i].getRarity(),
                                attractorLocations[i].getPower_old(),
                                attractorLocations[i].getProbability_single(),
                                attractorLocations[i].getIntegral_score(),
                                attractorLocations[i].getSignificance(),
                                attractorLocations[i].getProbability(),
                                attractorLocations[i].getFILTERING_SIGNIFICANCE(),
                                attractorLocations[i].getType(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getPower(),
                                attractorLocations[i].getZ_score(),
                                0, 0);

                        locationList.add(singleLocation);

                    }

                    i++;
                }

                //Check for anomaly
                if(selected == "Anomalie"){
                    for (int c = count - 1; c > 0; c--) { //Start bubblesort
                        for (int j = 0; j < c; j++) {
                            if (attractorLocations[j + 1] == null) {
                                continue;
                            }
                            if (attractorLocations[j] == null || attractorLocations[j + 1].compareTo(attractorLocations[j]) < 0) {
                                AttractorLocation temp = attractorLocations[j + 1];
                                attractorLocations[j + 1] = attractorLocations[j];
                                attractorLocations[j] = temp;
                            }
                        }
                    } //End bubblesort
                    for(i = 0; i < count; i++){

                        //Make databaseHelper
                        mDatabaseHelper = new DatabaseHelper(context, anomalyTable);

                        //Generate Marker
                        mapboxMap.addMarker(new MarkerOptions()
                                .position(new LatLng(attractorLocations[i].getCoordinate().getLatitude(),  attractorLocations[i].getCoordinate().getLongitude()))
                                .title("Attractor"));

                        //Generate Circle
                        mapboxMap.addPolygon(generatePerimeter(
                                new LatLng( attractorLocations[i].getCoordinate().getLatitude(),  attractorLocations[i].getCoordinate().getLongitude()),
                                (attractorLocations[i].getRadiusM()/1000),
                                64));

                        amount++;
                        MyRandonautFragment.anomalies++;
                        SingleRecyclerViewLocation singleLocation = new SingleRecyclerViewLocation();
                        singleLocation.setType((attractorLocations[i].getType()));
                        singleLocation.setRadiusm((attractorLocations[i].getRadiusM()));
                        singleLocation.setPower((attractorLocations[i].getPower()));
                        singleLocation.setZ_score((attractorLocations[i].getZ_score()));
                        singleLocation.setLocationCoordinates(attractorLocations[i].getCoordinate());
                        singleLocation.setPsuedo(false);

                        AddData(anomalyTable,
                                attractorLocations[i].getCoordinate().getLatitude(),
                                attractorLocations[i].getCoordinate().getLongitude(),
                                attractorLocations[i].getGID(),
                                attractorLocations[i].getTID(),
                                attractorLocations[i].getLID(),

                                attractorLocations[i].getX(),
                                attractorLocations[i].getY(),
                                attractorLocations[i].getDistance(),
                                attractorLocations[i].getInitialBearing(),
                                attractorLocations[i].getFinalBearing(),
                                attractorLocations[i].getSide(),
                                attractorLocations[i].getDistanceErr(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getN(),
                                attractorLocations[i].getMean(),
                                attractorLocations[i].getRarity(),
                                attractorLocations[i].getPower_old(),
                                attractorLocations[i].getProbability_single(),
                                attractorLocations[i].getIntegral_score(),
                                attractorLocations[i].getSignificance(),
                                attractorLocations[i].getProbability(),
                                attractorLocations[i].getFILTERING_SIGNIFICANCE(),
                                attractorLocations[i].getType(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getPower(),
                                attractorLocations[i].getZ_score(),
                                0, 0);

                        locationList.add(singleLocation);

                        i ++;
                    }



                } //End anomaly

                if(amount > 0){
                    randonautDialogsListener.onData(locationList);
                    MyRandonautFragment.startButton.setVisibility(View.GONE);
                    // navigateButton.setVisibility(View.VISIBLE);
                    MyRandonautFragment.resetButton.setVisibility(View.VISIBLE);
                } else {
                    //Nothhing was found
                    onCreateDialog(context, selected);
                }

                //saveData();
                progressdialog.dismiss();
            }

            @Override
            public void onFailure(Call<List<Attractors>> call, Throwable t) {
                progressdialog.dismiss();
                onCreateDialog(context, selected);
            }


        });
    }

    public void getAttractorsFromSetEntropy(final View view, final MapboxMap mapboxMap, final Context context,
                              String GID, boolean pool, boolean temporal, boolean gcp, final String selected, int distance, final RandonautAttractorListener randonautDialogsListener){
        //Empty previous run
        locationList = new ArrayList<>();
        mapboxMap.clear();
        //removeRecyclerView(view);

        //Start ProgressDialog
        progressdialog = new ProgressDialog(context);
        progressdialog.setMessage("Looking for " + selected + "s " + "please wait....");
        progressdialog.show();
        progressdialog.setCancelable(false);
        progressdialog.setCanceledOnTouchOutside(false);

        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .connectTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .build();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(new String(Base64.decode(MyRandonautFragment.getBaseApi(),Base64.DEFAULT)))
                .client(okHttpClient)
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        randoWrapperApi = retrofit.create(RandoWrapperApi.class);

        Call<List<Attractors>> callGetAttractors = randoWrapperApi.getAttractors(GID,
                mapboxMap.getLocationComponent().getLastKnownLocation().getLatitude(), mapboxMap.getLocationComponent().getLastKnownLocation().getLongitude(), distance, pool, temporal, gcp);

        callGetAttractors.enqueue(new Callback<List<Attractors>>() {
            @Override
            public void onResponse(Call<List<Attractors>> call, Response<List<Attractors>> response) {

                int i = 0;
                int count = 0;
                int amount = 0;

                for(Attractors attractors: response.body()){
                    count ++;
                }

                AttractorLocation attractorLocations[] =new AttractorLocation[count];

                for(Attractors attractors: response.body()){

                    //First Part
                    String GID = attractors.getAttractors().getGID();
                    String TID = attractors.getAttractors().getTID();
                    String LID = attractors.getAttractors().getLID();
                    int type = attractors.getAttractors().getType();
                    double x_ = attractors.getAttractors().getX();
                    double y_ = attractors.getAttractors().getY();


                    //Second part
                    double x = attractors.getAttractors().getCenter().getLatlng().getPoint().getLatitude(); //Used in map
                    double y = attractors.getAttractors().getCenter().getLatlng().getPoint().getLongitude(); //Used in map

                    double distance = attractors.getAttractors().getCenter().getLatlng().getBearing().getDistance();
                    double initialBearing = attractors.getAttractors().getCenter().getLatlng().getBearing().getInitialBearing();
                    double finalBearing = attractors.getAttractors().getCenter().getLatlng().getBearing().getFinalBearing();

                    //Third part
                    int side = attractors.getAttractors().getSide();
                    double distanceErr = attractors.getAttractors().getDistanceErr();
                    double radiusM = attractors.getAttractors().getRadiusM();
                    int n = attractors.getAttractors().getN();
                    double mean = attractors.getAttractors().getMean();
                    int rarity = attractors.getAttractors().getRarity();
                    double power_old = attractors.getAttractors().getPower_old();
                    double power = attractors.getAttractors().getPower();
                    double z_score = attractors.getAttractors().getZ_score();
                    double probability_single = attractors.getAttractors().getProbability_single();
                    double integral_score = attractors.getAttractors().getIntegral_score();
                    double significance = attractors.getAttractors().getSignificance();
                    double probability = attractors.getAttractors().getProbability();
                    int FILTERING_SIGNIFICANCE = attractors.getAttractors().getFILTERING_SIGNIFICANCE();

                    attractorLocations[i]=new AttractorLocation(new LatLng(x, y), GID,  TID,  LID,  x_,  y_,  distance,  initialBearing,  finalBearing, side,  distanceErr,  radiusM, n,  mean, rarity,  power_old,  probability_single,  integral_score,  significance,  probability, FILTERING_SIGNIFICANCE, type, radiusM,  power,  z_score);

                    if(type == 1){
                        //Make databaseHelper
                        mDatabaseHelper = new DatabaseHelper(context, attractorTable);

                        //Generate Marker
                        mapboxMap.addMarker(new MarkerOptions()
                                .position(new LatLng(x, y))
                                .title("Attractor"));

                        //Generate Circle
                        mapboxMap.addPolygon(generatePerimeter(
                                new LatLng(x, y),
                                (radiusM/1000),
                                64));

                        amount++;
                        MyRandonautFragment.atts++;
                        SingleRecyclerViewLocation singleLocation = new SingleRecyclerViewLocation();
                        singleLocation.setType((attractorLocations[i].getType()));
                        singleLocation.setRadiusm((attractorLocations[i].getRadiusM()));
                        singleLocation.setPower((attractorLocations[i].getPower()));
                        singleLocation.setZ_score((attractorLocations[i].getZ_score()));
                        singleLocation.setLocationCoordinates(attractorLocations[i].getCoordinate());
                        singleLocation.setPsuedo(false);

                        AddData(attractorTable,
                                attractorLocations[i].getCoordinate().getLatitude(),
                                attractorLocations[i].getCoordinate().getLongitude(),
                                attractorLocations[i].getGID(),
                                attractorLocations[i].getTID(),
                                attractorLocations[i].getLID(),

                                attractorLocations[i].getX(),
                                attractorLocations[i].getY(),
                                attractorLocations[i].getDistance(),
                                attractorLocations[i].getInitialBearing(),
                                attractorLocations[i].getFinalBearing(),
                                attractorLocations[i].getSide(),
                                attractorLocations[i].getDistanceErr(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getN(),
                                attractorLocations[i].getMean(),
                                attractorLocations[i].getRarity(),
                                attractorLocations[i].getPower_old(),
                                attractorLocations[i].getProbability_single(),
                                attractorLocations[i].getIntegral_score(),
                                attractorLocations[i].getSignificance(),
                                attractorLocations[i].getProbability(),
                                attractorLocations[i].getFILTERING_SIGNIFICANCE(),
                                attractorLocations[i].getType(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getPower(),
                                attractorLocations[i].getZ_score(),
                                0, 0);

                        locationList.add(singleLocation);

                    }

                    if(type == 2){
                        mDatabaseHelper = new DatabaseHelper(context, voidTable);

                        //Generate Marker
                        mapboxMap.addMarker(new MarkerOptions()
                                .position(new LatLng(x, y))
                                .title("Void"));

                        //Generate Circle
                        mapboxMap.addPolygon(generatePerimeter(
                                new LatLng(x, y),
                                (attractorLocations[i].getRadiusM()/1000),
                                64));

                        amount++;
                        MyRandonautFragment.voids++;
                        SingleRecyclerViewLocation singleLocation = new SingleRecyclerViewLocation();
                        singleLocation.setType((attractorLocations[i].getType()));
                        singleLocation.setRadiusm((attractorLocations[i].getRadiusM()));
                        singleLocation.setPower((attractorLocations[i].getPower()));
                        singleLocation.setZ_score((attractorLocations[i].getZ_score()));
                        singleLocation.setLocationCoordinates(attractorLocations[i].getCoordinate());
                        singleLocation.setPsuedo(false);

                        AddData(voidTable,
                                attractorLocations[i].getCoordinate().getLatitude(),
                                attractorLocations[i].getCoordinate().getLongitude(),
                                attractorLocations[i].getGID(),
                                attractorLocations[i].getTID(),
                                attractorLocations[i].getLID(),

                                attractorLocations[i].getX(),
                                attractorLocations[i].getY(),
                                attractorLocations[i].getDistance(),
                                attractorLocations[i].getInitialBearing(),
                                attractorLocations[i].getFinalBearing(),
                                attractorLocations[i].getSide(),
                                attractorLocations[i].getDistanceErr(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getN(),
                                attractorLocations[i].getMean(),
                                attractorLocations[i].getRarity(),
                                attractorLocations[i].getPower_old(),
                                attractorLocations[i].getProbability_single(),
                                attractorLocations[i].getIntegral_score(),
                                attractorLocations[i].getSignificance(),
                                attractorLocations[i].getProbability(),
                                attractorLocations[i].getFILTERING_SIGNIFICANCE(),
                                attractorLocations[i].getType(),
                                attractorLocations[i].getRadiusM(),
                                attractorLocations[i].getPower(),
                                attractorLocations[i].getZ_score(),
                                0, 0);

                        locationList.add(singleLocation);

                    }

                    i++;
                }

                if(amount > 0){
                    randonautDialogsListener.onData(locationList);
                    MyRandonautFragment.startButton.setVisibility(View.GONE);
                    // navigateButton.setVisibility(View.VISIBLE);
                    MyRandonautFragment.resetButton.setVisibility(View.VISIBLE);
                } else {
                    //Nothhing was found
                    onCreateDialog(context, selected);
                }

                //saveData();
                progressdialog.dismiss();
            }

            @Override
            public void onFailure(Call<List<Attractors>> call, Throwable t) {
                progressdialog.dismiss();
            }


        });
    }

    public void getPsuedo(final View view, final MapboxMap mapboxMap, final Context context,
                          final int distance, final String selected, final RandonautAttractorListener randonautDialogsListener) {

        //Empty previous run
        locationList = new ArrayList<>();
        mapboxMap.clear();
       // removeRecyclerView(view);

        //Start ProgressDialog
        progressdialog = new ProgressDialog(context);
        progressdialog.setMessage("Looking for " + selected + "s " + "please wait....");
        progressdialog.show();
        progressdialog.setCancelable(false);
        progressdialog.setCanceledOnTouchOutside(false);

        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .connectTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .build();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(new String(Base64.decode(MyRandonautFragment.getBaseApi(),Base64.DEFAULT)))
                .client(okHttpClient)
                .addConverterFactory(GsonConverterFactory.create())
                .build();

        randoWrapperApi = retrofit.create(RandoWrapperApi.class);

        Call<Sizes> callGetSizes = randoWrapperApi.getSizes(distance);

        callGetSizes.enqueue(new Callback<Sizes>() {
            @Override
            public void onResponse(Call<Sizes> call, Response<Sizes> response) {

                N = response.body().getN();

                int seed = 0;
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
                    seed = ThreadLocalRandom.current().nextInt(0, 2147483647);
                } else {
                    seed = 23;
                }
                Call<List<PseudoAttractor>> callGetPsuedo = randoWrapperApi.getPsuedo(N,
                        mapboxMap.getLocationComponent().getLastKnownLocation().getLatitude(), mapboxMap.getLocationComponent().getLastKnownLocation().getLongitude(), distance, seed, 4);

                callGetPsuedo.enqueue(new Callback<List<PseudoAttractor>>() {
                    @Override
                    public void onResponse(Call<List<PseudoAttractor>> call, Response<List<PseudoAttractor>> response) {
                        int i = 0;
                        int count = 0;
                        int amount = 0;

                        for (PseudoAttractor psuedos : response.body()) {
                            count++;
                        }

                        AttractorLocation attractorLocations[] = new AttractorLocation[count];


                        for (PseudoAttractor psuedos : response.body()) {

                            //First Part
                            String GID = psuedos.getGID();
                            String TID = psuedos.getTID();
                            String LID = psuedos.getLID();
                            int type = psuedos.getType();
                            double x_ = psuedos.getX();
                            double y_ = psuedos.getY();

                            //Second part
                            double x = psuedos.getLatitude(); //Used in map
                            double y = psuedos.getLongitude(); //Used in map

                            double distance = psuedos.getDistance();
                            double initialBearing = psuedos.getInitialBearing();
                            double finalBearing = psuedos.getFinalBearing();

                            //Third part
                            int side = psuedos.getSide();
                            double distanceErr = psuedos.getDistanceErr();
                            double radiusM = psuedos.getRadiusM();
                            int n = psuedos.getN();
                            double mean = psuedos.getMean();
                            int rarity = psuedos.getRarity();
                            double power_old = psuedos.getPower_old();
                            double power = psuedos.getPower();
                            double z_score = psuedos.getZ_score();
                            double probability_single = psuedos.getProbability_single();
                            double integral_score = psuedos.getIntegral_score();
                            double significance = psuedos.getSignificance();
                            double probability = psuedos.getProbability();
                            int FILTERING_SIGNIFICANCE = psuedos.getFILTERING_SIGNIFICANCE();

                            attractorLocations[i]=new AttractorLocation(new LatLng(x, y), GID,  TID,  LID,  x_,  y_,  distance,  initialBearing,  finalBearing, side,  distanceErr,  radiusM, n,  mean, rarity,  power_old,  probability_single,  integral_score,  significance,  probability, FILTERING_SIGNIFICANCE, type, radiusM,  power,  z_score);


                            if(type == 1) {
                                mDatabaseHelper = new DatabaseHelper(context, attractorTable);
                                mapboxMap.addMarker(new MarkerOptions()
                                        .position(new LatLng(x, y))
                                        .title("Attractor"));

                                //Generate Circle
                                mapboxMap.addPolygon(generatePerimeter(
                                        new LatLng(x, y),
                                        (radiusM/1000),
                                        64));

                                amount++;
                                MyRandonautFragment.psuedo++;
                                SingleRecyclerViewLocation singleLocation = new SingleRecyclerViewLocation();
                                singleLocation.setType((attractorLocations[i].getType()));
                                singleLocation.setRadiusm((attractorLocations[i].getRadiusm()));
                                singleLocation.setPower((attractorLocations[i].getPower()));
                                singleLocation.setZ_score((attractorLocations[i].getZ_score()));
                                singleLocation.setLocationCoordinates(attractorLocations[i].getCoordinate());
                                singleLocation.setPsuedo(true);

                                locationList.add(singleLocation);

                                AddData(voidTable,
                                        attractorLocations[i].getCoordinate().getLatitude(),
                                        attractorLocations[i].getCoordinate().getLongitude(),
                                        attractorLocations[i].getGID(),
                                        attractorLocations[i].getTID(),
                                        attractorLocations[i].getLID(),

                                        attractorLocations[i].getX(),
                                        attractorLocations[i].getY(),
                                        attractorLocations[i].getDistance(),
                                        attractorLocations[i].getInitialBearing(),
                                        attractorLocations[i].getFinalBearing(),
                                        attractorLocations[i].getSide(),
                                        attractorLocations[i].getDistanceErr(),
                                        attractorLocations[i].getRadiusM(),
                                        attractorLocations[i].getN(),
                                        attractorLocations[i].getMean(),
                                        attractorLocations[i].getRarity(),
                                        attractorLocations[i].getPower_old(),
                                        attractorLocations[i].getProbability_single(),
                                        attractorLocations[i].getIntegral_score(),
                                        attractorLocations[i].getSignificance(),
                                        attractorLocations[i].getProbability(),
                                        attractorLocations[i].getFILTERING_SIGNIFICANCE(),
                                        attractorLocations[i].getType(),
                                        attractorLocations[i].getRadiusM(),
                                        attractorLocations[i].getPower(),
                                        attractorLocations[i].getZ_score(),
                                        1, 0);
                            }

                            if(type == 2) {
                                mDatabaseHelper = new DatabaseHelper(context, voidTable);
                                mapboxMap.addMarker(new MarkerOptions()
                                        .position(new LatLng(x, y))
                                        .title("Void"));

                                //Generate Circle
                                mapboxMap.addPolygon(generatePerimeter(
                                        new LatLng(x, y),
                                        (attractorLocations[i].getRadiusM()/1000),
                                        64));

                                amount++;
                                MyRandonautFragment.psuedo++;
                                SingleRecyclerViewLocation singleLocation = new SingleRecyclerViewLocation();
                                singleLocation.setType((attractorLocations[i].getType()));
                                singleLocation.setRadiusm((attractorLocations[i].getRadiusm()));
                                singleLocation.setPower((attractorLocations[i].getPower()));
                                singleLocation.setZ_score((attractorLocations[i].getZ_score()));
                                singleLocation.setLocationCoordinates(attractorLocations[i].getCoordinate());
                                singleLocation.setPsuedo(true);

                                locationList.add(singleLocation);

                                AddData(voidTable,
                                        attractorLocations[i].getCoordinate().getLatitude(),
                                        attractorLocations[i].getCoordinate().getLongitude(),
                                        attractorLocations[i].getGID(),
                                        attractorLocations[i].getTID(),
                                        attractorLocations[i].getLID(),

                                        attractorLocations[i].getX(),
                                        attractorLocations[i].getY(),
                                        attractorLocations[i].getDistance(),
                                        attractorLocations[i].getInitialBearing(),
                                        attractorLocations[i].getFinalBearing(),
                                        attractorLocations[i].getSide(),
                                        attractorLocations[i].getDistanceErr(),
                                        attractorLocations[i].getRadiusM(),
                                        attractorLocations[i].getN(),
                                        attractorLocations[i].getMean(),
                                        attractorLocations[i].getRarity(),
                                        attractorLocations[i].getPower_old(),
                                        attractorLocations[i].getProbability_single(),
                                        attractorLocations[i].getIntegral_score(),
                                        attractorLocations[i].getSignificance(),
                                        attractorLocations[i].getProbability(),
                                        attractorLocations[i].getFILTERING_SIGNIFICANCE(),
                                        attractorLocations[i].getType(),
                                        attractorLocations[i].getRadiusM(),
                                        attractorLocations[i].getPower(),
                                        attractorLocations[i].getZ_score(),
                                        1, 0);

                            }


                            i++;

                        }

                        if(amount > 0){
                            //initRecyclerView(context, view, mapboxMap);
                            randonautDialogsListener.onData(locationList);
                            MyRandonautFragment.startButton.setVisibility(View.GONE);
                            //   navigateButton.setVisibility(View.VISIBLE);
                            MyRandonautFragment.resetButton.setVisibility(View.VISIBLE);
                        } else {

                            onCreateDialog(context, selected);
                        }
                     //   saveData();
                        progressdialog.dismiss();


                    }

                    @Override
                    public void onFailure(Call<List<PseudoAttractor>> call, Throwable t) {
                        onCreateDialog(context, selected);
                        progressdialog.dismiss();
                    }
                });


            }

            @Override
            public void onFailure(Call<Sizes> call, Throwable t) {

            }

        });
    }

    public void onCreateDialog(Context context, String selected) {

        new AlertDialog.Builder(context)
                .setTitle("No " + selected + "s found")
                .setMessage("Oops! No clear quantum points derived. Sometimes quantum generation takes a couple of tries. Go again!")

                // Specifying a listener allows you to take an action before dismissing the dialog.
                // The dialog is automatically dismissed when a dialog button is clicked.
                .setPositiveButton(android.R.string.yes, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {
                        // Continue with delete operation
                    }
                })

                .setIcon(android.R.drawable.ic_dialog_alert)
                .show();
    }

    /**
     * Draw circle on the mapview
     */
    public PolygonOptions generatePerimeter(LatLng centerCoordinates, double radiusInKilometers, int numberOfSides) {
        List<LatLng> positions = new ArrayList<>();
        double distanceX = radiusInKilometers / (111.319 * Math.cos(centerCoordinates.getLatitude() * Math.PI / 180));
        double distanceY = radiusInKilometers / 110.574;

        double slice = (2 * Math.PI) / numberOfSides;

        double theta;
        double x;
        double y;
        LatLng position;
        for (int i = 0; i < numberOfSides; ++i) {
            theta = i * slice;
            x = distanceX * Math.cos(theta);
            y = distanceY * Math.sin(theta);

            position = new LatLng(centerCoordinates.getLatitude() + y,
                    centerCoordinates.getLongitude() + x);
            positions.add(position);
        }
        return new PolygonOptions()
                .addAll(positions)
                .fillColor(Color.BLUE)
                .alpha(0.4f);
    }

    //Write to Database
    public void AddData (String table,double x, double y, String GID, String TID, String LID, double x_, double y_, double distance, double initialBearing, double finalBearing, int side, double distanceErr, double radiusM, int n, double mean, int rarity, double power_old, double probability_single, double integral_score, double significance, double probability, int FILTERING_SIGNIFICANCE, int type, double radiusm, double power, double z_score,double pseudo, int report) {
        boolean insertData = mDatabaseHelper.addData(table, x,  y,  GID,  TID,  LID,  x_,  y_,  distance,  initialBearing,  finalBearing,  side,  distanceErr,  radiusM,  n,  mean,  rarity,  power_old,  probability_single,  integral_score,  significance,  probability,  FILTERING_SIGNIFICANCE,  type,  radiusm,  power,  z_score, pseudo,  report);

        if (insertData){

        } else {

        }
    }


}